### ISSUE TITLE
添加好友异常

### ISSUE THREAD

**Issue by ABKQPO** [Agnes4m/nonebot_plugin_friends#1]
08-09 20:31:46 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_friends) failed.
Traceback (most recent call last):
  File "D:\NoneBot\ABK\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_friends\__init__.py", line 101, in _
    await pass_request(None, bot)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_friends\event.py", line 59, in pass_request
    friend_requests = await get_request_data()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_friends\event.py", line 19, in get_request_data
    friend_requests: List[Friend_request] = [
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_friends\event.py", line 20, in <listcomp>
    Friend_request.parse_obj(friend_dict)
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for Friend_request
add_nickname
  field required (type=value_error.missing)
add_message_id
  field required (type=value_error.missing)

**Comment by Agnes4m** [comment]
pydantic版本过高的问题，指定版本1.10.7或者其他低版本即可
